export const weddingConfig = {
  groom: {
    name: '장재균',
    englishName: 'Groom',
    father: '장병국',
    mother: '김은미',
    fatherDeceased: false,
    motherDeceased: false,
    phone: '010-3322-2306',
    fatherPhone: '010-4407-3840',
    motherPhone: '010-3439-4579',
  },
  bride: {
    name: '배유빈',
    englishName: 'Bride',
    father: '배동춘',
    mother: '김진경',
    fatherDeceased: false,
    motherDeceased: false,
    phone: '010-7756-5340',
    fatherPhone: '010-2863-5340',
    motherPhone: '010-2795-5340',
  },
  mainPhoto: '/wedding-invitation/images/main.jpg',
  date: '2026-11-28T14:00:00',
  greeting: {
    title: '결혼합니다',
    message:
      '여전히 같이 노는 게 누구보다 재밌고\n서로를 통해 함께하는 세상을 배워나갑니다.\n\n같은 하늘을 보고 서로를 노래하면서\n춤을 추고 부지런히 사랑하겠습니다.\n\n행복한 이 순간\n함께 해주시면 좋겠습니다.',
  },
  location: {
    name: '더메리든',
    hall: '8층',
    region: '경기도 성남시 분당구',   // 예식 안내에 표기되는 지역명
    address: '경기 성남시 분당구 서현로180번길 19',
    roadAddress: '경기 성남시 분당구 서현로180번길 19 비전월드',
    mapImageUrl: '',
    lat: 37.3855,
    lng: 127.1230,
    naverMapUrl: 'https://naver.me/GzE979EN',
    kakaoMapUrl: 'https://kko.to/em0e0lXI6p',
    tmapUrl: 'https://poi.tmobiweb.com/app/share/position?contents=cGtleT01NjkxNDcwMDAmcG9pSWQ9NTY5MTQ3MCZuYXZTZXE9MCZ0eXBlPTImcG9pTmFtZT0lRUIlOEQlOTQlRUIlQTklOTQlRUIlQTYlQUMlRUIlOTMlQTAmY2VudGVyWD00NTc2NDg0JmNlbnRlclk9MTM0NTg0MiZ0aW1lPTIwMjYlRUIlODUlODQrMDMlRUMlOUIlOTQrMjUlRUMlOUQlQkMrMDElM0E0MyZ0ZWw9MDMxLTcwNS0zMDMzJmFkZHI9JUVBJUIyJUJEJUVBJUI4JUIwKyVFQyU4NCVCMSVFQiU4MiVBOCVFQyU4QiU5QyslRUIlQjYlODQlRUIlOEIlQjklRUElQjUlQUMrJUVDJTg0JTlDJUVEJTk4JTg0JUViJUExJTlDMTgwJUVCJUIyJTg4JUVBJUI4JUI4KzE5&tailParam=%7B%22reqType%22%3A%220%22%2C%22reqMode%22%3A%221100%22%2C%22extra%22%3A%22112%22%7D',
    transport: [
      { type: '지하철', detail: '수인분당선 서현역 5번 출구에서 도보 5분' },
      { type: '주차', detail: '건물 내 주차장 이용 가능 (2시간30분 무료)' },
      {
        type: '대절버스',
        detail:
          '08:30 삼천포 공설운동장 출발\n09:10 서진주 만남의광장 경유\n상세 정보는 신부 측 연락 부탁드립니다.',
      },
    ],
  },
  accounts: {
    groom: [
      { bank: '국민은행', number: '498102-01-351089', holder: '장재균' },
      { bank: '신한은행', number: '110-062-277680', holder: '장병국' },
      { bank: '농협은행', number: '302-1203-7408-91', holder: '김은미' },
    ],
    bride: [
      { bank: '케이뱅크', number: '100-195-850093', holder: '배유빈' },
      { bank: '농협은행', number: '827012-52-069684', holder: '배동춘' },
      { bank: '농협은행', number: '827012-51-023044', holder: '김진경' },
    ],
  },
  gallery: [
    '/wedding-invitation/images/gallery/photo1.jpg',
    '/wedding-invitation/images/gallery/photo2.jpg',
    '/wedding-invitation/images/gallery/photo3.jpg',
    '/wedding-invitation/images/gallery/photo4.jpg',
    '/wedding-invitation/images/gallery/photo5.jpg',
    '/wedding-invitation/images/gallery/photo6.jpg',
    '/wedding-invitation/images/gallery/photo7.jpg',
    '/wedding-invitation/images/gallery/photo8.jpg',
    '/wedding-invitation/images/gallery/photo9.jpg',
    '/wedding-invitation/images/gallery/photo10.jpg',
    '/wedding-invitation/images/gallery/photo11.jpg',
    '/wedding-invitation/images/gallery/photo12.jpg',
    '/wedding-invitation/images/gallery/photo13.jpg',
    '/wedding-invitation/images/gallery/photo14.jpg',
    '/wedding-invitation/images/gallery/photo15.jpg',
    '/wedding-invitation/images/gallery/photo16.jpg',
    '/wedding-invitation/images/gallery/photo17.jpg',
    '/wedding-invitation/images/gallery/photo18.jpg',
    '/wedding-invitation/images/gallery/photo19.jpg',
    '/wedding-invitation/images/gallery/photo20.jpg',
  ],
}
